services:
  pipeline:
    build: .
    image: fita-direct-payments:latest
    container_name: fita-pipeline
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    ports:
      - "5000:5000"
    restart: "no"